import "../globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Oshofree",
  description: "Generated by create next app",
};

export default function MembershipLayout({ children }) {
  return (
    <html lang="en" className={plusJakartaSans.className}>
      <body className="overflow-y-auto scroll-smooth subpixel-antialiased scrollbar-track-red-200 scrollbar-thumb-red-500 scrollbar-track-rounded-full scrollbar-thumb-rounded-full before:block before:h-[1px] before:bg-red-500 xl:scrollbar-thin">
        {children}
      </body>
    </html>
  );
}
